name: Ruff

on:
  pull_request:
  push:
    branches:
      - master

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ruff:
    name: Check formatting and linting
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Check out repository
        uses: actions/checkout@v7

      - name: Check linting
        uses: astral-sh/ruff-action@v3
        with:
          version: 0.15.16
          args: check --output-format=github .

      - name: Check formatting
        uses: astral-sh/ruff-action@v3
        with:
          version: 0.15.16
          args: format --check .
